spring:
  application:
    name: clientcontractapi

  # ======================================================
  # DATABASE CONFIGURATION
  # ======================================================
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:h2:file:./data/api_factory_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true # force to wait the creation of database tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # ======================================================
  # JSON SERIALIZATION CONFIGURATION
  # ======================================================
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX   # ISO 8601 format
    time-zone: UTC                         

  # ======================================================
  # SECURITY CONFIGURATION
  # ======================================================
  security:
    jwt:
      secret: "secret-key-change-me-in-production"  # moved it to env variable in production
      expiration: 86400000                  # Token validity in milliseconds (1 day)

# ======================================================
# SERVER CONFIGURATION
# ======================================================
server:
  port: 8080
  error:
    include-message: always                 # Include detailed messages in error responses
    include-binding-errors: always          # Show validation errors in API responses

## Custom logs
logging:
  level:
    root: INFO
    com.apifactory.clientcontractapi: INFO

  file:
    path: ./logs 
    name: ./logs/app.log                       # <— triggers file logging

  logback:
    rollingpolicy:
      max-file-size: 10MB                    # <— correct key name
      max-history: 7                         # keep 7 rotated logs
      total-size-cap: 100MB                  # optional: global size cap
      clean-history-on-start: true           # refresh old logs each startup

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"


# ======================================================
# BACKUP CONFIGURATION
# ======================================================
backup:
  enabled: true
  cron: "0 0 * * * *"                      # Daily backup at midnight
  folder: ./backups                        # Folder for database backup files
