spring:
  application:
    name: clientcontractapi

  # ======================================================
  # DATABASE CONFIGURATION
  # ======================================================
  datasource:
    # File mode ensures data persistence between app restarts
    url: jdbc:h2:file:./data/api_factory_db
    driver-class-name: org.h2.Driver
    username: user_db
    password: password

  h2:
    console:
      enabled: true        
      path: /h2-console    # Accessible at http://localhost:8080/h2-console

  jpa:
    hibernate:
      ddl-auto: update     # Automatically creates/updates tables based on entities
    show-sql: true         
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # ======================================================
  # JSON SERIALIZATION CONFIGURATION
  # ======================================================
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX   # ISO 8601 format
    time-zone: UTC                         

  # ======================================================
  # SECURITY CONFIGURATION
  # ======================================================
  security:
    jwt:
      secret: "super-secret-key-change-me"  # moved it to env variable in production
      expiration: 86400000                  # Token validity in milliseconds (1 day)

# ======================================================
# SERVER CONFIGURATION
# ======================================================
server:
  port: 8080
  error:
    include-message: always                 # Include detailed messages in error responses
    include-binding-errors: always          # Show validation errors in API responses

# ======================================================
# LOGGING CONFIGURATION
# ======================================================
logging:
  level:
    root: WARN                               # Hide most Spring noise
    org.springframework: WARN
    org.hibernate: WARN
    com.apifactory.clientcontractapi: INFO   # Only log your own classes to file

  ## Custom logs
  file:
    name: ./logs/app.log
    max-size: 10MB
    max-history: 7

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    console: "%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"

# ======================================================
# BACKUP CONFIGURATION
# ======================================================
backup:
  enabled: true
  cron: "0 0 * * * *"                      # Daily backup at midnight
  folder: ./backups                        # Folder for database backup files
